FROM golang:alpine AS modules
RUN apk add --no-cache git
COPY go.mod go.sum /modules/
WORKDIR /modules
RUN go mod download

FROM golang:alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY --from=modules /go/pkg /go/pkg
COPY . .
RUN go mod tidy -x && \
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /bin/app ./cmd

FROM scratch
COPY --from=builder /app/config /config
COPY --from=builder /app/.env /.env
COPY --from=builder /bin/app /app
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
CMD ["/app"]