// Package order_v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package order_v1

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for PaymentMethod.
const (
	CARD      PaymentMethod = "CARD"
	CASH      PaymentMethod = "CASH"
	SBP       PaymentMethod = "SBP"
	UNDEFINED PaymentMethod = "UNDEFINED"
)

// Defines values for StatusOrder.
const (
	CANCELLED StatusOrder = "CANCELLED"
	NOTPAID   StatusOrder = "NOT_PAID"
	PAID      StatusOrder = "PAID"
)

// BadRequestError defines model for bad_request_error.
type BadRequestError struct {
	// Code HTTP-код
	Code int `json:"code"`

	// Message Не верный запрос
	Message string `json:"message"`
}

// CreateOrderRequest defines model for create_order_request.
type CreateOrderRequest struct {
	// HardwareUuids Список UUID компонентов в заказе
	HardwareUuids []openapi_types.UUID `json:"hardware_uuids"`

	// UserUuid UUID пользователя
	UserUuid openapi_types.UUID `json:"user_uuid"`
}

// CreateOrderResponse defines model for create_order_response.
type CreateOrderResponse struct {
	// CreatedAt Время создания
	CreatedAt time.Time `json:"created_at"`

	// OrderUuid UUID заказа
	OrderUuid openapi_types.UUID `json:"order_uuid"`

	// Status Статус платежа
	//   - NOT_PAID: не оплачено
	//   - PAID: оплачено
	//   - CANCELLED: Отменён
	Status StatusOrder `json:"status"`

	// TotalPrice Стоимость заказа
	TotalPrice float32 `json:"total_price"`
}

// GenericError defines model for generic_error.
type GenericError struct {
	// Code HTTP-код ошибки
	Code int `json:"code"`

	// Message Что то пошло не так
	Message string `json:"message"`
}

// GetOrderResponse defines model for get_order_response.
type GetOrderResponse struct {
	// CreatedAt Время создания
	CreatedAt time.Time `json:"created_at"`

	// HardwareUuids Список комплектующих
	HardwareUuids []openapi_types.UUID `json:"hardware_uuids"`

	// OrderUuid UUID заказа
	OrderUuid openapi_types.UUID `json:"order_uuid"`
	Payment   *Payment           `json:"payment,omitempty"`

	// Status Статус платежа
	//   - NOT_PAID: не оплачено
	//   - PAID: оплачено
	//   - CANCELLED: Отменён
	Status StatusOrder `json:"status"`

	// TotalPrice Стоимость заказа
	TotalPrice float32 `json:"total_price"`

	// UpdatedAt Время последнего обновления
	UpdatedAt time.Time `json:"updated_at"`

	// UserUuid UUID пользователя
	UserUuid openapi_types.UUID `json:"user_uuid"`
}

// InternalServerError defines model for internal_server_error.
type InternalServerError struct {
	// Code HTTP-код
	Code int `json:"code"`

	// Message Ошибка сервера
	Message string `json:"message"`
}

// NotFoundError defines model for not_found_error.
type NotFoundError struct {
	// Code HTTP-код
	Code int `json:"code"`

	// Message Заказ не найден
	Message string `json:"message"`
}

// Payment defines model for payment.
type Payment struct {
	// CreatedAt Время создания
	CreatedAt time.Time `json:"created_at"`

	// PaymentMethod Способ оплаты
	// - UNDEFINED: не определенный
	// - CASH: оплата наличными
	// - CARD: оплата картой
	// - SBP: оплата через СБП
	PaymentMethod PaymentMethod `json:"payment_method"`

	// TransactionUuid UUID транзакции
	TransactionUuid openapi_types.UUID `json:"transaction_uuid"`

	// UpdatedAt Время последнего обновления
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// PaymentMethod Способ оплаты
// - UNDEFINED: не определенный
// - CASH: оплата наличными
// - CARD: оплата картой
// - SBP: оплата через СБП
type PaymentMethod string

// PaymentOrderRequest defines model for payment_order_request.
type PaymentOrderRequest struct {
	// PaymentMethod Способ оплаты
	// - UNDEFINED: не определенный
	// - CASH: оплата наличными
	// - CARD: оплата картой
	// - SBP: оплата через СБП
	PaymentMethod PaymentMethod `json:"payment_method"`
}

// PaymentOrderResponse defines model for payment_order_response.
type PaymentOrderResponse struct {
	// TransactionUuid Уникальный идентификатор транзакции
	TransactionUuid openapi_types.UUID `json:"transaction_uuid"`

	// UpdatedAt Время последнего обновления
	UpdatedAt time.Time `json:"updated_at"`
}

// StatusOrder Статус платежа
//   - NOT_PAID: не оплачено
//   - PAID: оплачено
//   - CANCELLED: Отменён
type StatusOrder string

// OrderUuid defines model for order_uuid.
type OrderUuid = openapi_types.UUID

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = CreateOrderRequest

// PayOrderJSONRequestBody defines body for PayOrder for application/json ContentType.
type PayOrderJSONRequestBody = PaymentOrderRequest
