openapi: 3.0.0
info:
  title: Computer assembly service
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1
    description: Dev server
paths:
  /order:
    $ref: paths/order.yaml
  /order/{order_uuid}:
    $ref: paths/order_{order_uuid}.yaml
  /order/{order_uuid}/cancel:
    $ref: paths/order_{order_uuid}_cancel.yaml
  /order/{order_uuid}/pay:
    $ref: paths/order_{order_uuid}_pay.yaml
x-ogen:
  target: ./shared/api/order/v1
  package: order_v1
  clean: true
