// Package order_v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package order_v1

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Create Order
	// (POST /api/v1/order)
	CreateOrder(ctx echo.Context) error
	// Get order by uuid
	// (GET /api/v1/orders/{order_uuid})
	GetOrder(ctx echo.Context, orderUuid OrderUuid) error
	// Cancel order
	// (POST /api/v1/orders/{order_uuid}/cancel)
	CancelOrder(ctx echo.Context, orderUuid OrderUuid) error
	// Payment order
	// (POST /api/v1/orders/{order_uuid}/pay)
	PayOrder(ctx echo.Context, orderUuid OrderUuid) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CreateOrder converts echo context to params.
func (w *ServerInterfaceWrapper) CreateOrder(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateOrder(ctx)
	return err
}

// GetOrder converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrder(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "order_uuid" -------------
	var orderUuid OrderUuid

	err = runtime.BindStyledParameterWithOptions("simple", "order_uuid", ctx.Param("order_uuid"), &orderUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order_uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOrder(ctx, orderUuid)
	return err
}

// CancelOrder converts echo context to params.
func (w *ServerInterfaceWrapper) CancelOrder(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "order_uuid" -------------
	var orderUuid OrderUuid

	err = runtime.BindStyledParameterWithOptions("simple", "order_uuid", ctx.Param("order_uuid"), &orderUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order_uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CancelOrder(ctx, orderUuid)
	return err
}

// PayOrder converts echo context to params.
func (w *ServerInterfaceWrapper) PayOrder(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "order_uuid" -------------
	var orderUuid OrderUuid

	err = runtime.BindStyledParameterWithOptions("simple", "order_uuid", ctx.Param("order_uuid"), &orderUuid, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter order_uuid: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PayOrder(ctx, orderUuid)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/api/v1/order", wrapper.CreateOrder)
	router.GET(baseURL+"/api/v1/orders/:order_uuid", wrapper.GetOrder)
	router.POST(baseURL+"/api/v1/orders/:order_uuid/cancel", wrapper.CancelOrder)
	router.POST(baseURL+"/api/v1/orders/:order_uuid/pay", wrapper.PayOrder)

}
